In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
%matplotlib inline
import csv

In [2]:
train = pd.read_csv("train.csv",header=None)
trainlabels = pd.read_csv("trainLabels.csv",header=None)

test = pd.read_csv("test.csv",header=None)

In [3]:
print(train.head())
print(trainlabels.head())

         0         1         2         3         4         5         6   \
0  0.299403 -1.226624  1.498425 -1.176150  5.289853  0.208297  2.404498   
1 -1.174176  0.332157  0.949919 -1.285328  2.199061 -0.151268 -0.427039   
2  1.192222 -0.414371  0.067054 -2.233568  3.658881  0.089007  0.203439   
3  1.573270 -0.580318 -0.866332 -0.603812  3.125716  0.870321 -0.161992   
4 -0.613071 -0.644204  1.112558 -0.032397  3.490142 -0.011935  1.443521   

         7         8         9     ...           30        31        32  \
0  1.594506 -0.051608  0.663234    ...    -0.850465 -0.622990 -1.833057   
1  2.619246 -0.765884 -0.093780    ...    -0.819750  0.012037  2.038836   
2 -4.219054 -1.184919 -1.240310    ...    -0.604501  0.750054 -3.360521   
3  4.499666  1.038741 -1.092716    ...     1.022959  1.275598 -3.480110   
4 -4.290282 -1.761308  0.807652    ...     0.513906 -1.803473  0.518579   

         33        34        35        36        37        38        39  
0  0.293024  3.552681  0

In [4]:
print(train.shape)
print(trainlabels.shape)
print(test.shape)

(1000, 40)
(1000, 1)
(9000, 40)


In [5]:
alltrain = pd.concat([train, trainlabels], axis=1)

In [6]:
alltrain.head()

0         1         2         3         4         5         6   \
0  0.299403 -1.226624  1.498425 -1.176150  5.289853  0.208297  2.404498   
1 -1.174176  0.332157  0.949919 -1.285328  2.199061 -0.151268 -0.427039   
2  1.192222 -0.414371  0.067054 -2.233568  3.658881  0.089007  0.203439   
3  1.573270 -0.580318 -0.866332 -0.603812  3.125716  0.870321 -0.161992   
4 -0.613071 -0.644204  1.112558 -0.032397  3.490142 -0.011935  1.443521   

         7         8         9  ...        31        32        33        34  \
0  1.594506 -0.051608  0.663234 ... -0.622990 -1.833057  0.293024  3.552681   
1  2.619246 -0.765884 -0.093780 ...  0.012037  2.038836  0.468579 -0.517657   
2 -4.219054 -1.184919 -1.240310 ...  0.750054 -3.360521  0.856988 -2.751451   
3  4.499666  1.038741 -1.092716 ...  1.275598 -3.480110 -1.065252  2.153133   
4 -4.290282 -1.761308  0.807652 ... -1.803473  0.518579 -0.205029 -4.744566   

         35        36        37        38        39  0   
0  0.717611  3.305972 -2.715559 -2.682409  0.101050   1  
1  0.422326  0.803699  1.213219  1.382932 -1.817761   0  
2 -1.582735  1.672246  0.656438 -0.932473  2.987436   0  
3  1.563539  2.767117  0.215748  0.619645  1.883397   1  
4 -1.520015  1.830651  0.870772 -1.894609  0.408332   0  

[5 rows x 41 columns]

In [7]:
#As it is a Classification Problem,
#We will try basic Logistic Regression in first try

In [8]:
#Importing the additional libraries
from sklearn import datasets, neighbors, linear_model

In [9]:
#Train Test Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train,trainlabels, test_size=0.25, random_state=0)

In [10]:
print (x_train.shape, y_train.shape)
print (x_test.shape, y_test.shape)

(750, 40) (750, 1)
(250, 40) (250, 1)


In [11]:
#Modelling
logistic = linear_model.LogisticRegression(C=1e5)
logistic.fit(x_train,y_train)

C:\Users\SAN\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [12]:
y_pred = logistic.predict(x_test)


In [13]:
from sklearn.metrics import mean_squared_error, r2_score

In [14]:
# The coefficients
print('Coefficients: \n', logistic.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y_test,y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

Coefficients: 
 [[-0.10711323 -0.05005448 -0.04634891  0.16460314  0.1255605   0.01048875
  -0.04342508  0.04448899 -0.02598613  0.23135067 -0.03393262 -0.02293113
   0.23155007  0.14729982  0.34994443 -0.179452   -0.00311351 -0.09453181
   0.09841487  0.10864475 -0.15301657 -0.20089149  0.15241736 -0.07138361
   0.07264287 -0.06191085  0.11873377 -0.09858747 -0.0659265  -0.06457525
  -0.11548218 -0.00367056 -0.17389181 -0.14473517  0.29781705  0.10447987
  -0.22366922  0.12213753 -0.13101063  0.42457149]]
Mean squared error: 0.17
Variance score: 0.31


In [15]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix

In [16]:
confusion_matrix(y_test, y_pred)

array([[ 90,  24],
       [ 19, 117]], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.82799999999999996

In [18]:
y_pred

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [19]:
y_pred_test = logistic.predict(test)

In [22]:
y_pred_test

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [31]:
ID = range(9000)

In [30]:
from pandas import DataFrame
df = DataFrame({'ID': ID, 'Solution': y_pred_test})
df.to_excel('test1.xlsx', sheet_name='sheet1', index=False)

In [ ]:
import csv
from itertools import izip

with open('some.csv', 'wb') as f:
    writer = csv.writer(f)
    writer.writerows(izip(bins, frequencies))