In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5,6,7,8,9]
arr = np.array(list)

In [6]:
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
list1= [[0,1,2],[3,4,5],[6,7,8]]
arr1 = np.array(list1)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
list = [1,2,3,4,5,6,7,8,9]
arr = np.array(list,dtype='float')
arr
##Float type 

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
print('Shape: ', arr.shape)
# dtype
print('Datatype: ', arr.dtype)
# size
print('Size: ', arr.size)
# ndim
print('Num Dimensions: ', arr.ndim)

Shape:  (9,)
Datatype:  float64
Size:  9
Num Dimensions:  1


In [10]:
# mean, max and min
print("Mean value is: ", arr.mean())
print("Max value is: ", arr.max())
print("Min value is: ", arr.min())

Mean value is:  5.0
Max value is:  9.0
Min value is:  1.0


In [15]:
#New array from existing array
arr2 = arr1[:1,:1]  
arr2[:1, :1] = 100  # 100 will reflect in arr2
arr2

array([[100,   1],
       [  3,   4]])

In [18]:
## index locations that satisfy a given condition
newarr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [22]:
# Positions where value > 5
pos = np.where(newarr > 5)
print("Positions where value > 5: ", pos)

Positions where value > 5:  (array([0, 1, 3, 4], dtype=int64),)


In [26]:
date = np.datetime64('2018-02-04 23:10:10')
date

numpy.datetime64('2018-02-04T23:10:10')

In [27]:
dt = np.datetime64(date, 'D')
dt

numpy.datetime64('2018-02-04')

In [30]:
m = np.datetime64(date, 'm')
s = np.datetime64(date, 's')
ns = np.datetime64(date, 'ns')

print(m)
print(s)
print(ns)

2018-02-04T23:10
2018-02-04T23:10:10
2018-02-04T23:10:10.000000000
